services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      - TZ=Australia/Sydney
      - WEBPASSWORD=${WEBPASSWORD}
      - DNSMASQ_LISTENING=all
    volumes:
      - /docker/appdata/pihole/pihole:/etc/pihole
      - /docker/appdata/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
