services:
  mariadb:
    container_name: 'mariadb'
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'memtly'
      MYSQL_USER: '${MARIADB_USER}'
      MYSQL_PASSWORD: '${MARIADB_PASSWORD}'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data-volume-mariadb:/var/lib/mysql:rw
    networks:
      - memtly-net
    hostname: 'mariadb'
    restart: 'unless-stopped'
  memtly:
    container_name: Memtly
    image: memtly/memtly:latest
    ports:
      - '${MEMTLY_HTTP_PORT:-8080}:5000/tcp'
    environment:
      TITLE: '${TITLE}'
      ACCOUNT_ADMIN_PASSWORD: '${ACCOUNT_OWNER_PASSWORD}'
      ACCOUNT_REGISTRATION_ENABLED: false
      DATABASE_TYPE: 'mariadb'
      DATABASE_CONNECTION_STRING: 'Server=mariadb;Port=3306;Database=memtly;User=${MARIADB_USER};Password=${MARIADB_PASSWORD};'
      ENCRYPTION_KEY: '${ENCRYPTION_KEY}'
      ENCRYPTION_SALT: '${ENCRYPTION_SALT}'
      GALLERY_SELECTOR_DROPDOWN: true
      GALLERY_REQUIRE_REVIEW: false
      GALLERY_SECRET_KEY: '${GALLERY_SECRET_KEY}'
      GALLERY_MAX_SIZE_MB: 20000
      GALLERY_MAX_FILE_SIZE_MB: 50
      SINGLE_GALLERY_MODE: true
      THEMES_COLOUROVERRIDES_NAVBARTEXT: '#2C2825'
      THEMES_COLOUROVERRIDES_NAVBARBACKGROUND: '#F0ECE0'
      THEMES_COLOUROVERRIDES_BACKGROUND: '#F7F5E0'
      THEMES_COLOUROVERRIDES_PRIMARY1: '#C94F3A'
      THEMES_COLOUROVERRIDES_PRIMARY2: '#5B89F5'
      THEMES_COLOUROVERRIDES_PRIMARY3: '#C94F3A'
      THEMES_DEFAULT: 'Custom'
    volumes:
      - /docker/appdata/memtly/config:/app/config
      - /docker/appdata/memtly/thumbnails:/app/thumbnails
      - /docker/appdata/memtly/uploads:/app/uploads
      - /docker/appdata/memtly/custom_resources:/app/custom_resources
    networks:
      - memtly-net
    hostname: memtly
    restart: 'unless-stopped'
    depends_on:
      - mariadb
volumes:
  data-volume-mariadb:
    name: Memtly-MariaDB
networks:
  memtly-net:
    name: 'memtly-net'
    external: false
