version: "3.7"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    restart: "always"
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /docker/appdata/jellyfin:/config
      - /data:/media
      - /transcodes:/transcodes
    ports:
      - 8096:8096
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
