version: "3.7"
services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: "always"
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /docker/appdata/jellyfin:/config
      - /data:/media
      - /transcodes:/transcodes
    ports:
      - 8096:8096
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
  plex:
    container_name: plex
    image: hotio/plex
    restart: "always"
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Australia/Sydney
      - PLEX_PASS=no
      # - PLEX_CLAIM=claim-XXXXXXXXXXXXXXXXXXXX # Use PLEX_CLAIM on initial setup (https://www.plex.tv/claim/)
    volumes:
      - /docker/appdata/plex:/config
      - /data:/media
      - /transcodes:/transcodes
    ports:
      - "32400:32400"
